### ISSUE TITLE
Steps fails with error "tlsv1 alert protocol version"

### ISSUE THREAD

**Issue by fwigorcferreira** [bitrise-steplib/steps-github-status#10]
Recently, the step started to fail in the SSL connection, with the error `OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: tlsv1 alert protocol version`

Step details:

+------------------------------------------------------------------------------+

| (10) github-status@1.0.3                                                     |
+------------------------------------------------------------------------------+
| id: github-status                                                            |
| version: 1.0.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2018-02-23T02:49:22-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
  api_base_url: https://api.github.com
  repository_url: <GIT_REPO>
  commit_hash: <COMMIT\>
  ci_build_url: https://www.bitrise.io/build/<BUILD_ID\>
  authorization_token: ***
  build_is_green: true
  specific_status: 
  uri: https://api.github.com/repos/<REPO\>/statuses/\<COMMIT\>
#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: tlsv1 alert protocol version>
--- Stack trace: ---
["/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'", "/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'", "/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:948:in `connect'", "/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'", "/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:876:in `start'", "/usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/net/http.rb:1407:in `request'", "/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise122088654/step_src/github_status_helper.rb:97:in `perform'", "/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise122088654/step_src/step.rb:10:in `<main>'"]
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | github-status@1.0.3 (exit code: 1)                            | 5.29 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-github-status/issues |
| Source: https://github.com/bitrise-steplib/steps-github-status               |
+---+---------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Thanks for reporting and for the PR, your fix was released in v1.0.4 (https://github.com/bitrise-steplib/steps-github-status/releases/tag/1.0.4)! :)
