### ISSUE TITLE
Error: server error: 404 Not Found

### ISSUE THREAD

**Issue by adrienthiery** [bitrise-steplib/steps-github-status#16]
Hi there,

I added the Github status step to my workflow and created an Github API Token with the `repo:status` scope, but it never works, I get the following error:

```
+------------------------------------------------------------------------------+

| (3) github-status@2.1.0                                                      |
+------------------------------------------------------------------------------+
| id: github-status                                                            |
| version: 2.1.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2018-08-02T16:02:00-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
config:
- AuthToken: xxxxxxxxxxxxxxxxxxxxxxxx
- RepositoryURL: git@github.com:xxxxxx/xxxxxx.git
- CommitHash: 1e37403a2a7f453d85df88569d949ccdba38cd83
- APIURL: https://api.github.com
- State: auto
- BuildURL: https://app.bitrise.io/build/79a4867aae5a90af
- StatusIdentifier: continuous-integration/bitrise
- Description: 
Error: server error: 404 Not Found
exit status 1
WARN[16:02:05] Step (github-status@2.1.0) failed, but was marked as skippable 
```

Any idea why/how to fix it, please?

Or how to investigate?

**Comment by bitce** [comment]
Hi @adrienthiery!

Sorry for the inconvenience, the issue seems to be related to the GitHub servers directly. https://status.github.com/messages

There is not much we can do, but since they are on the case I would suggest waiting an hour or so as it will likely be resolved shortly.

**Comment by adrienthiery** [comment]
Weird, it's happening to me since I added the step (last week or so).

Let's see if it was related to github issues :) I'll reopen if it still occurs

**Comment by adrienthiery** [comment]
Hi @bitce ,

Reopening that 'cause github is back to normal but the error is still happening.

I was trying to investigate this, and actually it might be a right issue.

1) My repo is private, and part of my organization, it is not a personal repo
2) The token I created is a Personal Access Token, and I think it does not give access to that repo

Does it make it incompatible with the way you are using the GitHub API ?

**Comment by adrienthiery** [comment]
My solution, for anyone having that issue : 

* Created an OAuth App in my organisation
* Followed steps 1-2 of https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/
* Added the token I got like that to bitrise as a secret

**Comment by bitce** [comment]
Hey @adrienthiery!

Way to go! Sorry for assuming that the issue was exclusively caused by the GitHub issue, but all in all I'm glad to hear you found a workaround!
